version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.buildkite

  app-production: &production
    build: .
    environment:
      - BUILD_HASH=${BUILDKITE_COMMIT}

  app-staging:
    <<: *production
    environment:
      - DEPLOY_TARGET=staging
      - BUILD_HASH=${BUILDKITE_COMMIT}
