version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.buildkite

  app-production:
    build: &production-build
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_HASH=${BUILDKITE_COMMIT}

  app-staging:
    build:
      <<: *production-build
      args:
        - DEPLOY_TARGET=staging
        - BUILD_HASH=${BUILDKITE_COMMIT}
