version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.buildkite
      args:
        FA5_TOKEN: ${FA5_TOKEN}

  app-production: &production
    build:
      context: .
      args:
        FA5_TOKEN: ${FA5_TOKEN}

  app-staging:
    <<: *production
