steps:
  - label: ":docker: Build test image"
    plugins:
      - docker-compose#v2.6.0:
          build: app
          config: docker-compose.buildkite.yml

  - wait

  - label: ":yarn: Test"
    command: "yarn test"
    plugins:
      - docker-compose#v2.6.0:
          run: app
          config: docker-compose.buildkite.yml

  - label: ":yarn: :eslint: Lint"
    command: "yarn lint"
    plugins:
      - docker-compose#v2.6.0:
          run: app
          config: docker-compose.buildkite.yml

  - wait

  - label: ":docker: Build+Push `:staging` image"
    branches: "staging"
    plugins:
      - docker-login#v2.0.1:
          server: docker.csvalpha.nl
          username: buildkite
          password-env: DOCKER_PASSWORD
      - docker-compose#v2.6.0:
          push: app-production:docker.csvalpha.nl/amber-ui:staging
          config: docker-compose.buildkite.yml

  - label: ":docker: Build+Push `:production` image"
    branches: "master"
    plugins:
      - docker-login#v2.0.1:
          server: docker.csvalpha.nl
          username: buildkite
          password-env: DOCKER_PASSWORD
      - docker-compose#v2.6.0:
          push: app-production:docker.csvalpha.nl/amber-ui:latest
          config: docker-compose.buildkite.yml

  - block: "Deploy this stage"
    branches: "master staging"

  - label: 'Restarting service'
    command: 'bash .buildkite/release.sh'
    branches: "master staging"

  - wait

  - label: 'Inform Sentry'
    command: 'bash .buildkite/sentry.sh'
    branches: "master staging"

  - label: 'Inform Slack'
    command: 'bash .buildkite/slack.sh'
    branches: "master staging"
