name: Cleanup Registry

on:
  schedule:
    - cron: '0 0 * * 1' # https://crontab.guru/#0_0_*_*_1
  workflow_dispatch:

env:
  IMAGE_NAMES: amber-ui

jobs:
  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Delete old versions
        uses: snok/container-retention-policy@fdd5728f5b6918fbc30e24e0ca78ff1e6b378ea4 # tag=v1.4.1
        with:
          image-names: ${{ env.IMAGE_NAMES }}
          cut-off: 2 days ago UTC
          account-type: org
          org-name: ${{ github.repository_owner }}
          skip-tags: latest,staging
          token: ${{ secrets.PAT }}
